version: '3.8'

services:
    postgresql_database:
        container_name: otd_postgres_container
        image: postgres:latest
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=otd_db
        ports: 
            - "5431:5432"
        restart: always

    pgadmin:
        container_name: otd_pgadmin4_container
        image: dpage/pgadmin4
        environment: 
            - PGADMIN_DEFAULT_EMAIL=admin@admin.com
            - PGADMIN_DEFAULT_PASSWORD=password
        ports:
            - '5050:80'
        restart: always

    redis:
        container_name: otd_redis_container
        image: redis
        ports:
            - '6379:6379'
        restart: always